export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const GET_ID_START = 'GET_ID_START';
export const GET_ID_SUCCESS = 'GET_ID_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const LOADING_CATEGORY = 'LOADING_CATEGORY';
export const STOP_LOADING_CATEGORY = 'STOP_LOADING_CATEGORY';
export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';
export const SAVE_CATEGORY = 'SAVE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const LOADING_EXERCISE = 'LOADING_EXERCISE';
export const STOP_LOADING_EXERCISE = 'STOP_LOADING_EXERCISE';
export const GET_ALL_EXERCISE = 'GET_ALL_EXERCISE';
export const SAVE_EXERCISE = 'SAVE_EXERCISE';
export const UPDATE_EXERCISE = 'UPDATE_EXERCISE';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';

export const LOADING_START = 'LOADING_START';
export const STOP_LOADING_START = 'STOP_LOADING_START';
export const GET_START = 'GET_START';
export const SAVE_START = 'SAVE_START';
export const UPDATE_START = 'UPDATE_START';
export const DELETE_START = 'DELETE_START';

export const LOADING_WORKOUT_DAY = 'LOADING_WORKOUT_DAY';
export const STOP_LOADING_WORKOUT_DAY = 'STOP_LOADING_WORKOUT_DAY';
export const GET_WORKOUT_DAY = 'GET_WORKOUT_DAY';
export const SAVE_WORKOUT_DAY = 'SAVE_WORKOUT_DAY';
export const UPDATE_WORKOUT_DAY = 'UPDATE_WORKOUT_DAY';
export const DELETE_WORKOUT_DAY = 'DELETE_WORKOUT_DAY';

export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
