export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const GET_ID_START = 'GET_ID_START';
export const GET_ID_SUCCESS = 'GET_ID_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const LOADING_CATEGORY = 'LOADING_CATEGORY';
export const STOP_LOADING_CATEGORY = 'STOP_LOADING_CATEGORY';
export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';
export const SAVE_CATEGORY = 'SAVE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const LOADING_EXERCISE = 'LOADING_EXERCISE';
export const STOP_LOADING_EXERCISE = 'STOP_LOADING_EXERCISE';
export const GET_ALL_EXERCISE = 'GET_ALL_EXERCISE';
export const SAVE_EXERCISE = 'SAVE_EXERCISE';
export const UPDATE_EXERCISE = 'UPDATE_EXERCISE';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';

export const LOADING_MAIN_EXERCISE = 'LOADING_MAIN_EXERCISE';
export const STOP_LOADING_MAIN_EXERCISE = 'STOP_LOADING_MAIN_EXERCISE';
export const GET_MAIN_EXERCISE = 'GET_MAIN_EXERCISE';
export const UPDATE_MAIN_EXERCISE = 'UPDATE_MAIN_EXERCISE';

export const LOADING_ASSISTANCE_EXERCISE = 'LOADING_ASSISTANCE_EXERCISE';
export const STOP_LOADING_ASSISTANCE_EXERCISE = 'STOP_LOADING_ASSISTANCE_EXERCISE';
export const GET_ALL_ASSISTANCE_EXERCISE = 'GET_ALL_ASSISTANCE_EXERCISE';
export const SAVE_ASSISTANCE_EXERCISE = 'SAVE_ASSISTANCE_EXERCISE';
export const UPDATE_ASSISTANCE_EXERCISE = 'UPDATE_ASSISTANCE_EXERCISE';
export const DELETE_ASSISTANCE_EXERCISE = 'DELETE_ASSISTANCE_EXERCISE';

export const LOADING_START = 'LOADING_START';
export const STOP_LOADING_START = 'STOP_LOADING_START';
export const GET_START = 'GET_START';
export const SAVE_START = 'SAVE_START';
export const UPDATE_START = 'UPDATE_START';
export const DELETE_START = 'DELETE_START';

export const GET_WORKOUT = 'GET_WORKOUT';
export const LOADING_WORKOUT = 'LOADING_WORKOUT';
export const STOP_LOADING_WORKOUT = 'STOP_LOADING_WORKOUT';
export const SKIP_WORKOUT = 'SKIP_WORKOUT';
export const COMPLETE_WORKOUT = 'COMPLETE_WORKOUT';

export const LOADING_WORKOUT_DAY = 'LOADING_WORKOUT_DAY';
export const STOP_LOADING_WORKOUT_DAY = 'STOP_LOADING_WORKOUT_DAY';
export const GET_WORKOUT_DAY = 'GET_WORKOUT_DAY';
export const SAVE_WORKOUT_DAY = 'SAVE_WORKOUT_DAY';
export const UPDATE_WORKOUT_DAY = 'UPDATE_WORKOUT_DAY';
export const DELETE_WORKOUT_DAY = 'DELETE_WORKOUT_DAY';
export const ADD_EXERCISE_TO_WORKOUT = 'ADD_EXERCISE_TO_WORKOUT';
export const UPDATE_WORKOUT_SETS = 'UPDATE_WORKOUT_SETS';
export const DELETE_EXERCISE_FROM_WORKOUT = 'DELETE_EXERCISE_FROM_WORKOUT';

export const LOADING_ROUTINE_EXERCISE = 'LOADING_ROUTINE_EXERCISE';
export const STOP_LOADING_ROUTINE_EXERCISE = 'STOP_LOADING_ROUTINE_EXERCISE';
export const GET_ROUTINE_EXERCISE = 'GET_ROUTINE_EXERCISE';

export const START_REST_TIMER = 'START_REST_TIMER';
export const STOP_REST_TIMER = 'STOP_REST_TIMER';

export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
